version: '3.8'

services:
  # 데이터베이스 서비스 정의
  db:
    image: postgres:18 # 18 버전
    container_name: aicar-db # 컨테이너의 이름을 정합니다.
    restart: always # 에러가 나거나 재부팅 시 자동으로 다시 켭니다.
    environment:
      POSTGRES_USER: postgres # 접속할 사용자 아이디
      POSTGRES_PASSWORD: 1234 # 접속 비밀번호
      POSTGRES_DB: aicar # 생성할 데이터베이스 이름
    ports:
      - "5433:5432" # 내 컴퓨터의 5433 포트와 도커의 5432 포트를 연결합니다.

  redis:
    image: redis:8.6-alpine
    container_name: aicar-redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    environment:
      - REDIS_HOST=redis
  # 백엔드 서비스 정의
  # backend:
  #   build:
  #     context: .
  #     dockerfile: infra/docker/Dockerfile.backend # 레시피 파일의 위치
  #   container_name: aicar-backend
  #   ports:
  #     - "8080:8080" # 내 컴퓨터 포트 : 컨테이너 포트
  #   volumes:
  #     - ./backend:/app # 코드 수정을 실시간으로 반영하기 위한 연결
  #   env_file:
  #     - ./backend/.env.local # 로컬에서는 로컬
  #   environment:
  #     - DB_HOST=db # 나중에 추가할 DB 서비스 이름
  #     - DB_PORT=5432
  #   depends_on:
  #     - db
  #     - redis
