-- +goose Up
ALTER TABLE my_cars
ADD COLUMN IF NOT EXISTS brand VARCHAR(100),
ADD COLUMN IF NOT EXISTS model VARCHAR(100),
ADD COLUMN IF NOT EXISTS year INT,
ADD COLUMN IF NOT EXISTS fuel_type VARCHAR(50);

-- +goose Down
ALTER TABLE my_cars
DROP COLUMN IF EXISTS fuel_type,
DROP COLUMN IF EXISTS year,
DROP COLUMN IF EXISTS model,
DROP COLUMN IF EXISTS brand;